# Generated by Django 4.0.2 on 2022-02-21 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('city', models.CharField(max_length=400)),
                ('starRating', models.IntegerField()),
                ('amenities', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
