# Generated by Django 4.0.2 on 2022-02-26 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotelapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='finalCost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotel',
            name='noDaysBooked',
            field=models.IntegerField(default=0),
        ),
    ]
